
GET http://localhost:5000/customer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJsb2NhbGhvc3Q6NTAwMCIsImlzcyI6ImxvY2FsaG9zdDo1MDAwIiwiZXhwIjoxNzY4NDg4OTc2LCJzdWIiOiJiaWxsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4NDg1Mzc2LCJuYmYiOjE3Njg0ODUzNzZ9.HKhTmjYQjkH6B_DVbP33ampuZidc3Lwm-bbaV0V52RI

### 

GET http://localhost:5000/customer/greal

###

GET http://localhost:5000/customer/xxx

###

POST http://localhost:5000/customer
Content-Type: application/json
{
  "customerID": "BLGTS",
  "companyName": "Microsoft",
  "contactName": "Bill Gates"
}

###

PUT http://localhost:5000/customer/blgts
Content-Type: application/json
{
  "customerID": "BLGTS",
  "companyName": "Microsoft",
  "contactName": "William Gates"
}

###

DELETE http://localhost:5000/customer/blgts

###

POST http://localhost:5000/auth/login
Content-Type: application/json
{
  "email": "bill@example.com",
  "password": "abc123"
}